### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by MarcoMagriDev** [ADVRHumanoids/modularbots_fraunhofer#1]
By running the command:
```bash
. docker/run.sh 
```
The following error is reported:
```bash
[sudo] password for user: user is not in the sudoers file.  This incident will be reported.
Could neither symlink nor copy file "/opt/ros/noetic/share/catkin/cmake/toplevel.cmake" to "/home/user/catkin_ws/src/CMakeLists.txt":
- [Errno 13] Permission denied: '/opt/ros/noetic/share/catkin/cmake/toplevel.cmake' -> '/home/user/catkin_ws/src/CMakeLists.txt'
- [Errno 13] Permission denied: '/home/user/catkin_ws/src/CMakeLists.txt'Base path: /home/user/catkin_ws
Source space: /home/user/catkin_ws/src
Build space: /home/user/catkin_ws/build
[Errno 13] Permission denied: '/home/user/catkin_ws/build'
./setup_catkin_ws.sh: line 10: devel/setup.bash: No such file or directory
bash: /home/user/catkin_ws/devel/setup.bash: No such file or directory
```

So when i try to run `mon launch ModularBot_6DOF ModularBot_gazebo.launch` (as described in the simulation readme section) I get:
```bash
[rospack] Error: package 'ModularBot_6DOF' not found
Could not find path of package 'ModularBot_6DOF'
```
@alaurenzi this issue is blocking me on running the robot in Gazebo simulation environment.

**Comment by alaurenzi** [comment]
Hi @MarcoMagriDev ,
could you try to remove the line `-u $(id -u):$(id -g)` from the `run.sh` script?
I don't even know why it's there, maybe a copy-paste typo..

**Comment by MarcoMagriDev** [comment]
> Hi @MarcoMagriDev , could you try to remove the line `-u $(id -u):$(id -g)` from the `run.sh` script? I don't even know why it's there, maybe a copy-paste typo..

Thanks @alaurenzi your suggestion fixes the issue. Are you going to update the `run.sh` script or should i open a PR for that?

**Comment by alaurenzi** [comment]
Done, closing this issue. Thanks for reporting!
