### ISSUE TITLE
Unable to move the robot in simulation

### ISSUE THREAD

**Issue by MarcoMagriDev** [ADVRHumanoids/modularbots_fraunhofer#2]
### Description
When I try to send a command to the simulated robot I get:
```bash
[err ][rt_main] [J1_A] safety limit violation detected in delta tx (0.0  --->  0.009999999776482582): d(pos_ref)/dt exceeded: |9.999999| > 3.900000; 
[warn][rt_main] [J1_A] safety triggered: freezing qref and setting vref = 0, tauref = 0
[warn][rt_main] [J2_A] safety triggered: freezing qref and setting vref = 0, tauref = 0
[warn][rt_main] [J3_A] safety triggered: freezing qref and setting vref = 0, tauref = 0
[warn][rt_main] [J4_A] safety triggered: freezing qref and setting vref = 0, tauref = 0
[warn][rt_main] [J5_A] safety triggered: freezing qref and setting vref = 0, tauref = 0
[warn][rt_main] [J6_A] safety triggered: freezing qref and setting vref = 0, tauref = 0
```

### How to reproduce the issue
1) Follow instructions reported in https://github.com/ADVRHumanoids/modularbots_fraunhofer#running-the-simulation
2) Start a gui using the command `xbot2-gui` 
3) Enable `ros_ctrl` plugin
4) Enabl chain_A (joint panel of the gui)
5) Set the reference value for the joint J1_A to a small value (i.e. 0.01)
6) No motion will be performed and the error reported above will be printed

The same error is got if the motion is commanded using the `Continuous control` offered by the RViz interface spawned by `mon launch ModularBot_6DOF ModularBot_cartesio_IK.launch`

_Note: to use the command `mon launch ModularBot_6DOF ModularBot_cartesio_IK.launch` in your docker you will need to install manually some missing dependencies_

@alaurenzi have you any idea about how to solve this issue?

**Comment by alaurenzi** [comment]
See #3

**Comment by MarcoMagriDev** [comment]
Closing. See #3
